### ISSUE TITLE
error building rack-v2 against latest Rack V2 

### ISSUE THREAD

**Issue by davephillips** [mgunyho/PdArray#16]
Greetings ! I'm trying the build your rack-v2 branch with the latest Rack V2 but I get this error:

```
src/Array.cpp: In member function ‘virtual void ArrayDisplay::onDragMove(const DragMove&)’:
src/Array.cpp:452:40: error: ‘zoom’ is not a member of ‘rack::settings’
   float zoom = std::pow(2.f, settings::zoom);
                                        ^~~~

```

Andrew Belt replied to my inquiry this morning :

> The rack zoom level has been removed from global settings, since multiple Rack plugin instances need different zoom levels.
> 
> Why would a plugin need to get the rack zoom level…?
> 

Any suggestions for a fix ? I use the Array module a lot. :)

**Comment by mgunyho** [comment]
Cool that you're also interested in porting Array to Rack v2!

Yes, I noticed the same but didn't have more time to look into it. Apparently I use the zoom level to scale the mouse delta. You could try just removing it (replace `dragPosition = dragPosition.plus(e.mouseDelta.div(zoom))` with `dragPosition = dragPosition.plus(e.mouseDelta)`) and see if drawing works correctly with different zoom levels. This mouse drawing logic could also be improved I think, instead of computing the drag position from the previous value + delta, we should find out if it's possible to get the current mouse position reliably from the API. I don't recall why I did it this way originally, but maybe there was a reason for it.

**Comment by davephillips** [comment]
Hey, thank you for the quick response ! I built it without the zoom call, so far the module seems to behave as expected, except for one odd behavior: If I randomize and then select +10 for the Pos Range, the first value in the graph can't be changed, it defaults to mid-point and won't move. Curiously it can be changed without a problem if the Pos Range is +/-5 or +/-10.

**Comment by mgunyho** [comment]
I checked this just now with the `.div()` removed, but I'm seeing wrong behavior: with a zoom level other than 100%, dragging the mouse moves the bars an incorrect amount:

![Peek 2021-10-18 19-37](https://user-images.githubusercontent.com/20118130/137772916-9496a222-9620-4158-aa43-f2064ed1f96e.gif)


I'll check if I can get the mouse position somehow, instead of using this delta calculation which needs to be scaled with the zoom level.

**Comment by davephillips** [comment]
Andrew posted a bit more about it:

> You can get the RackScrollWidget's zoom level with APP->scene->rackScroll->getZoom() and a similar setter. Zoom levels are linear, not exponential like settings::zoom.

> Another purpose of zoom I’ve seen plugins use is conditional drawing of fine details to save CPU. For that, plugins should read the NanoVG state in draw() such as


```
float t[6];
nvgCurrentTransform(args.vg, t);
float zoom = t[3];
```

**Comment by mgunyho** [comment]
I fixed this now, and Array compiles for v2 (although with a bunch of deprecation warnings). Let me know if you notice any more issues!
