### ISSUE TITLE
feature suggestions

### ISSUE THREAD

**Issue by davephillips** [mgunyho/PdArray#19]
Greetings ! I use PdArray in almost every patch, but I'm missing a couple of features:

1) An option to play through the array once only.
2) An end-of-cycle (EOC) output.

These additions would be especially useful when creating large-scale formal envelopes.

Best regards,

dp

**Comment by mgunyho** [comment]
Hi! I'm glad you like it!

Could you elaborate a bit what you mean by "play through the array once only"? Is Miniramp not suitable for your use case?

About EOC, that is definitely something that could be added to Miniramp, although there isn't much space for additional output ports. Maybe I could add an option to the right-click menu, which would allow you to choose between outputting a gate, or an EOC pulse out of the current GATE output. How does that sound like?

As a workaround, you can use some module like HetricCV Delta to output a pulse when the ramp value is decreasing, which happens when the ramp ends (just make sure that the "ramp value when finished" option of Miniramp is set to 0V).

**Comment by davephillips** [comment]
> Hi! I'm glad you like it!

It's a great favorite here, I use it for a variety of purposes. What I would like to do is chain a series of ~array modules so that when one finishes it sends an EOC to the next module to trigger it. This way would allow me to build complex shapes using a modular approach rather than trying to write a very long shape into a single instance of the ~array module.

> Could you elaborate a bit what you mean by "play through the array once only"? Is Miniramp not suitable for your use case?

The "play once only" option is on the NYSTHI complexSimpler, it lets a soundfile play through one time only then stop rather than continue to loop. As described above, if the module could send an EOC I can then mix and match shapes more freely.

Alas, the Miniramp won't do what I need in this regard.

> About EOC, that is definitely something that could be added to Miniramp, although there isn't much space for additional output ports. Maybe I could add an option to the right-click menu, which would allow you to choose between outputting a gate, or an EOC pulse out of the current GATE output. How does that sound like?

I suppose that might work for the Miniramp. Can it be added to the ~array module as a separate output ?
 
> As a workaround, you can use some module like HetricCV Delta to output a pulse when the ramp value is decreasing, which happens when the ramp ends (just make sure that the "ramp value when finished" option of Miniramp is set to 0V).

That works pretty well for one of my purposes, i.e. to convert an edge to a trigger. I wish I'd have used it in this patch:

https://www.youtube.com/watch?v=U8D3u7Nj92s

I made an array module with 93 steps to control a chord sequence, then copied it and manually adjusted the copy to values of 0 and non-0 to trigger a synchronized display. At 93 steps the graphic entry becomes cramped and error-prone. It would be better/easier to compose long shapes by connecting shorter ones.

Please let me know if you need more information and/or a better description of what I'd like to achieve with the ~array module. Thank you ! 

Best regards,

Dave Phillips

**Comment by mgunyho** [comment]
Sorry for the delay.

> Can it be added to the array module as a separate output?

The problem is that "EOC" is not well defined for just the array itself. The array is not really "triggered", right? The playhead position is controlled by an external module like Miniramp (or which module have you been using?). The array really cannot know when the "cycle" ends; it might very well only go halfway into the array. Or the input to POS could be an audio signal, in which case the notion of EOC really makes no sense. (There also isn't much space left on the front panel for additional outputs.)

Based on the front panel, the NYSTHI complexSimpler takes a trigger input to play a sample, so it keeps track of the playhead position within itself. That makes it possible to tell when the EOC occurs.

Chaining together Arrays is a valid use case that is not easy to do at the moment. I think adding an EOC to Miniramp could help with that. I can implement that in the near future.

One trick you can use in the meanwhile is to increase the array size and then zoom in while drawing :) Not very elegant, but should make it easier to work with 90-element arrays.


HetrickCV is one of my favourite packs, it has lots of quite simple but very useful utility modules.

**Comment by davephillips** [comment]
> The problem is that "EOC" is not well defined for just the array itself. The array is not really "triggered", right? The playhead position is controlled by an external module like Miniramp (or which module have you been using?). The array really cannot know when the "cycle" ends; it might very well only go halfway into the array. Or the input to POS could be an audio signal, in which case the notion of EOC really makes no sense. (There also isn't much space left on the front panel for additional outputs.)

Normally I use LFOs to control the POS, and sometimes they do go back & forth without reaching the end of the displayed array. But I only need the EOC trigger when or if the playhead in fact does reach the final point of the array. Admittedly this could be problematic with the "play once through" option, and I see your point regarding the internal design issue.

> Chaining together Arrays is a valid use case that is not easy to do at the moment. I think adding an EOC to Miniramp could help with that. I can implement that in the near future.

I think I need to look into Miniramp to see how/if it can help me.

> HetrickCV is one of my favourite packs, it has lots of quite simple but very useful utility modules.

Agree++.

Thanks for the update and your consideration of the idea ! :)

dp

**Comment by mgunyho** [comment]
> I only need the EOC trigger when or if the playhead in fact does reach the final point of the array

But I don't think that's exactly what you want either. As a simple example, let's say  you have an array with five elements, and it advances to the next element every second, and after all five elements have been considered (played as chords or something), you want to move on to a new sequence. Now if the EOC is triggered when the last element is reached, you will start to play the next sequence already before having played the fifth chord. So the EOC should somehow be triggered when the cursor goes "beyond" the last element, but that's not really possible to do.

I think instead of an "play once through" option, the correct solution is to use a one-shot envelope generator instead of an LFO for the POS input, it's conceptually the right tool. Miniramp exists for this exact purpose, note that some envelope generators that try to emulate analog behavior can cause some artifacts (see e.g. [here](https://github.com/mgunyho/PdArray/issues/18)).

**Comment by davephillips** [comment]
> I think instead of an "play once through" option, the correct solution is to use a one-shot envelope generator instead of an LFO for the POS input, it's conceptually the right tool. Miniramp exists for this exact purpose, note that some envelope generators that try to emulate analog behavior can cause some artifacts...

That's a great idea, thanks for the tips re: Miniramp. I'll try some things with it today and will let you know how it works out.

**Comment by mgunyho** [comment]
Just so you know, I originally planned to add the EOC functionality to same port as the GATE of miniramp, with a right-click menu option to select whether the port would output GATE or EOC. But then I got carried away and added a bunch of other ports to Miniramp as well, here's a sneak peek:

![miniramp-wide](https://user-images.githubusercontent.com/20118130/211879430-1f3c63bb-b5c8-479d-84e5-7abafeb3b371.png)

(FIN is basically the NOT of GATE, it's high when GATE is low and vice versa.) Can you think of any additional things I could add while I'm at it?

**Comment by davephillips** [comment]
Very cool ! I've been working on using Miniramp/step, it's wonderful for the things I've been doing with the array module. I'm finding some interesting uses for it, I'll be happy to test anything you add to it. At the moment I can't think of anything else to add but I'll report back after working with it some more.

**Comment by mgunyho** [comment]
I've now updated Miniramp in version 2.1.0 with those new inputs, and it's now possible to chain easily!

![](https://raw.githubusercontent.com/mgunyho/PdArray/master/screenshots/envelope-chaining.png)

(In case you're wondering, the spikes you see in the oscilloscope have a length of a single sample, they can be removed using slew from VCV Fundamental.)

The update should be available on the plugin library soon.

I think this issue can be closed now, feel free to open a new one if you come across issues after the update.
