### ISSUE TITLE
array question

### ISSUE THREAD

**Issue by colundi** [mgunyho/PdArray#20]
excuse me attempting to contact you this way, i'm a newbie/unskilled and not sure of the protocol, but i have to ask... i love Array because i can play circular waves that i make in the nyquist prompt in audacity that i don't know how to make otherwise. Array plays them beautifully with no click. but i cannot work out how to change the pitch of the sample, with CV... is this possible, it would be so good. been wresting with what i want to do for a decade or more but my tech skills are stoneage. fair enough if you don't have time for this, thank you very much for sharing your work and well done and best wishes.

**Comment by mgunyho** [comment]
Hi! I'm glad you find Array useful! It's okay to ask help this way, there's not so much activity going on that it would be a problem. Another option could be the [VCV forums](https://community.vcvrack.com/), which I don't read that often but others might be able to help.

About your question: how are you reading the data from the array, what are you putting in as the CV for the play position? One way to accomplish a changing pitch is to use a sawtooth oscillator as the POS input, and then control the pitch of that oscillator using V/OCT:

![rack-array-pitch](https://github.com/mgunyho/PdArray/assets/20118130/28cf0931-585f-4290-a6b4-242762c8205c)


Here the pitch is controlled by the keyboard via the MIDI CV module, but you can use any other pitch modulation here, such as a sequencer. I'm using the wavetable VCO because the regular VCO sawtooth in Fundamental is not really a pure saw, because it's doing analog emulation, but any "digital" sawtooth should be fine.

**Comment by mgunyho** [comment]
Or if you are using Array to play longer samples, you can use an LFO to make the loop longer, or a phase-based oscillator such as [ZZC Clock](https://library.vcvrack.com/ZZC/Clock) for example, which you can use to pause/resume playback.

**Comment by mgunyho** [comment]
Hi! Was your problem solved? I'm closing this issue for now, but feel free to reopen it if you still need help.
