### ISSUE TITLE
Feature request: automatic resizing according to a sample

### ISSUE THREAD

**Issue by nesdnuma** [mgunyho/PdArray#9]
Hello,

It would be nice if the array could resize itself automatically according to a sample's size.

**Comment by mgunyho** [comment]
Hi, sorry it took me a while to respond.

That's a pretty good idea, but I'm not entirely sure how to go about it. The best way would be to have a checkbox in the file selection dialog, but I don't think the file picker supports that. Maybe there could be another menu option ("load .wav file and resize array"), although that might be a bit confusing. Or maybe the default behavior could be to just always resize the array, and the user can then manually change the sample count afterwards. What do you think?

**Comment by nesdnuma** [comment]
Hello,

I guess some people would be interested to avoid the array to be resized whenever they load a file into it. In this case an option to automatically resize would be the best option.

**Comment by mgunyho** [comment]
I've implemented this in the current master. There's now an option to load a file and resize the array or just load the file and keep the array otherwise unchanged. If you know how to compile Rack plugins, feel free to try if it works the way you expect.

I'm going to make some other small fixes and probably release a new version soonish, maybe by the end of the week.

**Comment by nesdnuma** [comment]
I am not able to compile Rack plugins sadly. I'll wait for the next update. Thanks a lot for the new feature!
